# host_vars/anchor.yml

home_shims_install_bashrc: true
pixi_enabled: false

use_selective_configs: true
starship_profile: "starship_anchor.toml"
use_zsh_shell: false
yazi_enabled: false

uv_enabled: false
cargo_crates_linux: []
poetry_projects_linux: []
uv_projects_linux: []

# Turn UniFi on for this host
unifi_enabled: false
unifi_use_mongodb36: false

docker_enabled: true
