brew_taps_extra:
  - epk/epk

brew_casks_extra:
  - font-sf-mono-nerd-font

desktop_casks_extra: []
desktop_casks_skip: []

# Include machine specfic apps like this:
#desktop_casks_extra:
#  - blender
#desktop_casks_skip:
#  - inkscape
