ORBIT_HOME: "{{ lookup('env','HOME') }}/.orbit"
ORBIT_DEV_HOME: "{{ lookup('env','HOME') }}/Dropbox/matrix/orbit"
ORBIT_REMOTE: "https://github.com/suhailphotos/orbit.git"
ORBIT_BRANCH: "main"

use_zsh_shell: true
