ORBIT_HOME: "{{ helix_user_home }}/.orbit"
ORBIT_DEV_HOME: "{{ helix_user_home }}/Dropbox/matrix/orbit"
ORBIT_REMOTE: "https://github.com/suhailphotos/orbit.git"
ORBIT_BRANCH: "main"

use_zsh_shell: true
uv_enabled: true

bindu_branch: "main"
