# Prefer existing vars if youâ€™ve already set matrix_root in group_vars
matrix_root: "{{ lookup('env','MATRIX') | default((ansible_facts['system'] == 'Darwin') | ternary(ansible_facts['env']['HOME'] + '/Library/CloudStorage/Dropbox/matrix', '/home/' + ansible_user + '/Dropbox/matrix'), true) }}"
atrium_root: "{{ matrix_root }}/atrium"

# list of stow package folder names under {{ atrium_root }}
# e.g. ['incept','notionmanager','oauthmanager','parivaha']
atrium_stow_packages: []

# first-run on a fresh box? set true to pull any existing ~ files into repo
atrium_use_adopt: false

# pass -R to restow (re-evaluate links); normally false
atrium_restow: false

# present => stow, absent => unstow
atrium_state: "present"

stow_bin: "stow"

# Tell stow to ignore junk files
stow_ignore_regexes:
  - '(^|/)\.DS_Store$'
  - '^\.stow-(local|global)-ignore$'
