bindu_mode: full
apogee_install_method: cargo
install_fish: true
install_powershell: true

brew_packages_extra:
  - fish

yazi_enabled: true
cargo_enabled: true
rustup_enabled: true

# --------------------------------------------------
#         Crates
# --------------------------------------------------
cargo_crates_macos:
  - { name: cargo-modules, bin: cargo-modules }
  - { name: cargo-watch,   bin: cargo-watch }
  # speed-ups: if you want binstall-first workflow, include it:
  - { name: cargo-binstall, bin: cargo-binstall }
