all:
  children:
    macos:
      hosts:
        eclipse:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
        quasar:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_host: "2603:8001:a000:101::20"
          ansible_user: suhail
          identity_file: "~/.ssh/id_quasar"
        feather:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    linux:
      hosts:
        flicker:
          ansible_host: flicker.suhail.ink
        nimbus:
          ansible_host: nimbus.suhail.ink
        nexus:
          ansible_host: nexus.suhail.ink

        # --- Proxmox nodes (shared client key) ---
        zion:
          ansible_host: "2603:8001:a000:100::cafe"
          ansible_user: root
          identity_file: "~/.ssh/id_proxmox"

        atlas:
          ansible_host: "2603:8001:a000:100::babe"
          ansible_user: root
          identity_file: "~/.ssh/id_proxmox"

        summit:                               # placeholder for third Proxmox node
          ansible_host: "2603:8001:a000:100::beef"    # or IPv6
          ansible_user: root
          identity_file: "~/.ssh/id_proxmox"

        # --- Raspberry Pi 5 ---
        wisp:
          ansible_host: "2603:8001:a000:100:98ec:d450:be2:8caa"
          ansible_user: suhail

        # --- Unifi Cloud Key ----
        anchor:
          ansible_host: 172.232.107.239
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/id_anchor"
